item1 = input("Digite o nome do primeiro item:")
quantidadeV = input("Digite a quantidade:")
item2 = input("Digite o nome do segundo item:")
quantidadeW = input("Digite a quantidade:")
item3 = input("Digite o nome do terceiro item:")
quantidadeY = input("Digite a quantidade:")
item4 = input("Digite o nome do quarto item:")
quantidadeX = input("Digite a quantidade:")
item5 = input("Digite o nome do quinto item:")
quantidadeZ = input("Digite a quantidade:")

print(f" {item1} - {quantidadeV}")
print(f" {item2} - {quantidadeW}")
print(f" {item3} - {quantidadeY}")
print(f" {item4} - {quantidadeX}")
print(f" {item5} - {quantidadeZ}")